name: test
"on": push

env:
  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: some rubbish

jobs:
  test_version_present:
    strategy:
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        cue:
          - v0.4.3
          - v0.5.0
          - v0.6.0-rc.1
          - latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Setup CUE
        uses: cue-lang/setup-cue@eb2a5424480e9a8c87ba140363abfc1bfa99fd58
        with:
          version: ${{ matrix.cue }}
      - name: Use CUE
        run: "cue version"
 
  test_version_missing:
    strategy:
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Setup CUE
        uses: cue-lang/setup-cue@eb2a5424480e9a8c87ba140363abfc1bfa99fd58
      - name: Use CUE
        run: "cue version"
